spring:
  application:
    name: hhplus-lecture
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: update
      #      ddl-auto: create
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    #    url: jdbc:h2:mem:test
    username: sa
    password: 1234
server:
  port: 8081
